apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: spring-prometheus
build:
  artifacts:
  - image: spring-prometheus
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - k8s/namespace.yml
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/service_monitor.yaml
