spring:
  application:
    name: hello-world-service

management:
  endpoints:
    web:
      exposure:
        include: metrics,health,info,env,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
