---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: hello-world-service
  name: hello-world-service
  labels:
    release: prometheus-operator # This name must match 'Prometheus Operator' release name!!!
spec:
  selector:
    matchLabels:
      app: hello-world-service
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"