apiVersion: v1
kind: Service
metadata:
  namespace: hello-world-service
  name: hello-world-service
  labels:
    app: hello-world-service
spec:
  selector:
    app: hello-world-service
  ports:
  - name: http-traffic
    port: 8080
    protocol: TCP
    targetPort: 8080