version: "2"
services:
  hello-world-service:
    image: spring-prometheus:0.0.1-SNAPSHOT
    container_name: hello-world-service
    restart: always
    ports:
      - 8080:8080
    environment:
      spring.profiles.active: docker

  prometheus:
    image: prom/prometheus:v2.26.0
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9090" ]
      start_period: 10s
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:7.5.2
    container_name: grafana
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]
      start_period: 10s
    ports:
      - 3000:3000
    environment:
      - "GF_USERS_ALLOW_SIGN_UP=false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
